# Generated by Django 3.2 on 2021-06-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('repeat_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1024)),
                ('message', models.TextField(max_length=2048)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendemail.usertype')),
            ],
        ),
    ]
